name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Jenkins Job
      uses: appleboy/jenkins-action@v0.2.0
      with:
        url: 'http://your-jenkins-server-url/job/your-jenkins-job-name/build'
        user: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_API_TOKEN }}
        # Optional parameters if your Jenkins job requires them
        parameters: |
          token=your-jenkins-job-token
          param1=value1
          param2=value2
